### ISSUE TITLE
[BUG]: 0.2.5 search java error

### ISSUE THREAD

**Issue by yondwell** [version-fox/vfox#121]
**Version**
0.2.5
**OS**
Windows11

**Describe the bug**
vfox search java

**Screenshots[optional]**
```
$ vfox search java
panic: reflect: call of reflect.Value.SetInt on string Value

goroutine 1 [running]:
reflect.Value.SetInt({0xd9da20?, 0xc0000615c0?, 0xc00008f6c0?}, 0x8)
        reflect/value.go:2336 +0xda
github.com/version-fox/vfox/internal/luai.storeLiteral({0xd9da20?, 0xc0000615c0?, 0xdf2260?}, {0xf1e700, 0xc0001e01f8})
        github.com/version-fox/vfox/internal/luai/decode.go:95 +0xc5
github.com/version-fox/vfox/internal/luai.unmarshalWorker({0xf1e700, 0xc0001e01f8}, {0xd9da20?, 0xc0000615c0?, 0xc000039e90?})
        github.com/version-fox/vfox/internal/luai/decode.go:280 +0x16f
github.com/version-fox/vfox/internal/luai.unmarshalWorker.func3({0xf1ddf8?, 0xc000039e90?}, {0xf1e700, 0xc0001e01f8})
        github.com/version-fox/vfox/internal/luai/decode.go:268 +0xe5
github.com/yuin/gopher-lua.(*LTable).ForEach(0xc000062ae0, 0xc00017ee80)
        github.com/yuin/gopher-lua@v1.1.1/table.go:337 +0x129
github.com/version-fox/vfox/internal/luai.unmarshalWorker({0xf1de20, 0xc000062ae0}, {0xd8ea20?, 0xc0000542a8?, 0x0?})
        github.com/version-fox/vfox/internal/luai/decode.go:250 +0x8c8
github.com/version-fox/vfox/internal/luai.unmarshalWorker.func2({0x3ff0000000000000?, 0xc00017f1f0?}, {0xf1de20, 0xc000062ae0})
        github.com/version-fox/vfox/internal/luai/decode.go:226 +0x1a5
github.com/yuin/gopher-lua.(*LTable).ForEach(0xc000062a80, 0xc00017f388)
        github.com/yuin/gopher-lua@v1.1.1/table.go:330 +0x2de
github.com/version-fox/vfox/internal/luai.unmarshalWorker({0xf1de20, 0xc000062a80}, {0xd97ee0?, 0xc000008708?, 0x18?})
        github.com/version-fox/vfox/internal/luai/decode.go:216 +0x2e5
github.com/version-fox/vfox/internal/luai.Unmarshal({0xf1de20?, 0xc000062a80?}, {0xd97ee0?, 0xc000008708?})
        github.com/version-fox/vfox/internal/luai/decode.go:293 +0xa7
github.com/version-fox/vfox/internal.(*LuaPlugin).Available(0xc0000b4120)
        github.com/version-fox/vfox/internal/plugin.go:92 +0x135
github.com/version-fox/vfox/internal.(*Sdk).Available(...)
        github.com/version-fox/vfox/internal/sdk.go:213
github.com/version-fox/vfox/cmd/commands.searchCmd(0xc00017fb10?)
        github.com/version-fox/vfox/cmd/commands/search.go:47 +0x1c5
github.com/urfave/cli/v2.(*Command).Run(0x12ea440, 0xc0000611c0, {0xc00003b580, 0x2, 0x2})
        github.com/urfave/cli/v2@v2.26.0/command.go:277 +0x9d8
github.com/urfave/cli/v2.(*Command).Run(0xc00015a420, 0xc000060d80, {0xc000060080, 0x3, 0x4})
        github.com/urfave/cli/v2@v2.26.0/command.go:270 +0xc25
github.com/urfave/cli/v2.(*App).RunContext(0xc0001b0780, {0xf1fad8?, 0x13489e0}, {0xc000060080, 0x3, 0x4})
        github.com/urfave/cli/v2@v2.26.0/app.go:335 +0x5db
github.com/urfave/cli/v2.(*App).Run(...)
        github.com/urfave/cli/v2@v2.26.0/app.go:309
github.com/version-fox/vfox/cmd.(*cmd).Execute(0x0?, {0xc000060080?, 0x0?, 0x60?})
        github.com/version-fox/vfox/cmd/cmd.go:39 +0x32
github.com/version-fox/vfox/cmd.Execute({0xc000060080, 0x3, 0x4})
        github.com/version-fox/vfox/cmd/cmd.go:30 +0x39
main.main()
        github.com/version-fox/vfox/main.go:25 +0x28
```

**Comment by aooohan** [comment]
Which plugin are you using?

**Comment by yondwell** [comment]
$ vfox info java
Plugin info:
Name      -> java
Author    -> aooohan
Version   -> 0.0.1
Desc      -> Adoptium JDK
UpdateUrl -> https://raw.githubusercontent.com/version-fox/version-fox-plugins/main/java/adoptium-jdk.lua

**Comment by yondwell** [comment]
Version 0.2.6 still exists

**Comment by aooohan** [comment]
I have fixed this issue. Please use `vfox update java` to upgrade.

**Comment by aooohan** [comment]
@bytemain The [reason](https://github.com/version-fox/version-fox-plugins/commit/4651d29e5f956aa46e120755ba249630f24c86ea) for this is that some of the version is of type int, whereas what we need is string, and besides forcing the plugin to return the string type, can we handle this in `vfox`?

**Comment by bytemain** [comment]
> @bytemain The [reason](https://github.com/version-fox/version-fox-plugins/commit/4651d29e5f956aa46e120755ba249630f24c86ea) for this is that some of the version is of type int, whereas what we need is string, and besides forcing the plugin to return the string type, can we handle this in `vfox`?

sure we can, I will make a pr later, the real reason is that we use this field's `lua type` to infer its `golang type`, actually we should inverse that, use one field's `golang type` and convert its type to specific golang type

![CleanShot 2024-03-19 at 10 27 13@2x](https://github.com/version-fox/vfox/assets/13938334/94070e53-2481-4b00-a7e2-b27e0de3acdb)
