### ISSUE TITLE
[BUG]: 重启电脑后第一次打开控制台环境变量失效

### ISSUE THREAD

**Issue by lianshuze** [version-fox/vfox#185]
**Version**
The version you are currently using
VersionFox version 0.2.4

**OS**
macOS、Linux、Windows
macbook pro m1 15+512 macos14.4.1 

**Describe the bug**
电脑重启后第一次打开控制台弹出一堆提示
panic: validate storage error: open /Library/Version Fox/.tmpfile: file exists

goroutine 1 [running]:
github.com/version-fox/vfox/internal.newSdkManager({0x1049e9260?, 0x140001b4870}, 0x14000074840)
        github.com/version-fox/vfox/internal/manager.go:434 +0x258
github.com/version-fox/vfox/internal.newSdkManagerWithSource({0x140001c58d8, 0x2, 0x140001c5768?})
        github.com/version-fox/vfox/internal/manager.go:410 +0x364
github.com/version-fox/vfox/internal.NewSdkManager({0x140001c58d8?, 0x10456e170?, 0x140001c5790?})
        github.com/version-fox/vfox/internal/manager.go:417 +0x6c
github.com/version-fox/vfox/cmd/commands.activateCmd(0x14000037180)
        github.com/version-fox/vfox/cmd/commands/activate.go:43 +0xd8
github.com/urfave/cli/v2.(*Command).Run(0x104d7aaa0, 0x14000037180, {0x14000073100, 0x2, 0x2})
        github.com/urfave/cli/v2@v2.26.0/command.go:277 +0x754
github.com/urfave/cli/v2.(*Command).Run(0x1400016a420, 0x14000036d80, {0x1400001e240, 0x3, 0x3})
        github.com/urfave/cli/v2@v2.26.0/command.go:270 +0x964
github.com/urfave/cli/v2.(*App).RunContext(0x14000172780, {0x1049e8f18?, 0x104dbad20}, {0x1400001e240, 0x3, 0x3})
        github.com/urfave/cli/v2@v2.26.0/app.go:335 +0x534
github.com/urfave/cli/v2.(*App).Run(...)
        github.com/urfave/cli/v2@v2.26.0/app.go:309
github.com/version-fox/vfox/cmd.(*cmd).Execute(0x14000032060?, {0x1400001e240?, 0x14000058728?, 0x0?})
        github.com/version-fox/vfox/cmd/cmd.go:37 +0x40
github.com/version-fox/vfox/cmd.Execute({0x1400001e240, 0x3, 0x3})
        github.com/version-fox/vfox/cmd/cmd.go:28 +0x38
main.main()
        github.com/version-fox/vfox/main.go:25 +0x34

紧跟着就是环境变量失效了
实际上我的机器之前已经设置过全局的环境变量重启之前还是正常使用，出现过很多次

**Screenshots[optional]**
<img width="602" alt="image" src="https://github.com/version-fox/vfox/assets/94230222/cfbb2cb7-af69-40b6-b08f-9773c70255e1">

**Comment by lianshuze** [comment]
补充一下，我新开一个命令行窗口就好了
